"use client";
import { useMemo, useState } from "react";

type Invoice = { id: string; invoice_number: string; customer_id: string; due_date: string; outstanding_amount: string; status: string };
const money = (value: string) => { const n = Number(value); return n >= 100000 ? `₹${(n / 100000).toFixed(1)}L` : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n); };
const statusTone = (status: string) => status === "PAID" ? "text-emerald-300 bg-emerald-400/[.08]" : status === "DISPUTED" ? "text-amber-200 bg-amber-300/[.08]" : status === "OVERDUE" ? "text-rose-300 bg-rose-400/[.08]" : "text-sky-300 bg-sky-400/[.08]";

export function InvoiceRegister({ invoices, customerNames }: { invoices: Invoice[]; customerNames: Map<string, string> }) {
  const pageSize = 30; const [page, setPage] = useState(0); const pages = Math.max(1, Math.ceil(invoices.length / pageSize));
  const rows = useMemo(() => invoices.slice(page * pageSize, (page + 1) * pageSize), [invoices, page]); const first = invoices.length ? page * pageSize + 1 : 0; const last = Math.min((page + 1) * pageSize, invoices.length);
  return <section className="mt-8 border border-white/[.09] bg-[#0d1627] shadow-[0_18px_45px_rgba(0,0,0,.16)]"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-white/[.07] p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-sky-300">Receivables register</p><p className="mt-1 text-lg font-semibold text-white">Invoice operations</p><p className="mt-1 text-xs text-slate-500">Live factual invoice records · no simulated client-side rows</p></div><div className="flex items-center gap-3 text-xs text-slate-400"><span>{first}–{last} of {invoices.length}</span><button aria-label="Previous invoice page" disabled={page === 0} onClick={() => setPage((value) => value - 1)} className="px-2 text-lg hover:text-white disabled:opacity-30">‹</button><button aria-label="Next invoice page" disabled={page >= pages - 1} onClick={() => setPage((value) => value + 1)} className="px-2 text-lg hover:text-white disabled:opacity-30">›</button></div></div><div className="overflow-x-auto"><div className="min-w-[850px]"><div className="grid grid-cols-[1.25fr_1fr_.75fr_.8fr_.8fr] gap-4 border-b border-white/[.06] px-5 py-3 text-[10px] font-bold uppercase tracking-[.13em] text-slate-600"><span>Invoice / account</span><span>Customer</span><span>Due date</span><span>Exposure</span><span>Status</span></div>{rows.map((invoice) => <div key={invoice.id} className="grid grid-cols-[1.25fr_1fr_.75fr_.8fr_.8fr] gap-4 border-b border-white/[.045] px-5 py-3 text-sm transition hover:bg-sky-400/[.03]"><div><p className="font-medium text-slate-200">{invoice.invoice_number}</p><p className="mt-0.5 text-[10px] text-slate-600">{invoice.id.slice(0, 8)}</p></div><p className="truncate text-slate-400">{customerNames.get(invoice.customer_id) ?? "Portfolio account"}</p><p className="text-slate-400">{invoice.due_date}</p><p className="font-semibold tabular-nums text-white">{money(invoice.outstanding_amount)}</p><span className={`w-fit px-2 py-1 text-[10px] font-bold tracking-[.08em] ${statusTone(invoice.status)}`}>{invoice.status}</span></div>)}</div></div></section>;
}
